### ISSUE TITLE
Move BLE assigned numbers to bt-hci

### ISSUE THREAD

**Issue by lulf** [embassy-rs/trouble#145]
There are several mentions of standard UUIDs, that should be moved to the [bt-hci](https://github.com/embassy-rs/bt-hci) crate. This would also involve moving the UUID type to bt-hci.

**Comment by jamessizeland** [comment]
https://github.com/embassy-rs/bt-hci/issues/17

**Comment by ScottGibb** [comment]
@jamessizeland Should this issue be closed now, or is there work to do on the Trouble Repo as well?

**Comment by jamessizeland** [comment]
this will be paused until the next release of bt-hci which includes the uuid export.

**Comment by lulf** [comment]
Moving this to the 0.1 milestone since it is merged now.
