### ISSUE TITLE
Add a way to validate/interact with a value before it gets put in AttributeTable

### ISSUE THREAD

**Issue by Erik1000** [embassy-rs/trouble#152]
Currently, you can only passively monitor the GattEvent. This is problematic in the case of `GattEvent::Write` because there is no way you can validate or inspect the value of the write event before it gets put into the AttributeTable and can then be read again.
It would be nice to hook into the write event to validate the value and (in case of error) discard it.

related to #151

**Comment by Erik1000** [comment]
I think in general it would be nice to be able to handle the actual values read and written better. For example, manually hook into reads and writes and controlling which value is sent or stored.

**Comment by jamessizeland** [comment]
@petekubiak has been looking at some of this, we're talking about some kind of middleware layer with callbacks essentially right?

**Comment by petekubiak** [comment]
I think this links closely with #135 - a draft PR (#133) is open to suggest ideas for how this might be achieved.

**Comment by petekubiak** [comment]
#151 is now up for review - I would be interested to hear your thoughts on the approach

**Comment by petekubiak** [comment]
@Erik1000 are you happy for this issue to be closed?

**Comment by Erik1000** [comment]
Yes
