### ISSUE TITLE
Add CI Publish to Crates.io Stage

### ISSUE THREAD

**Issue by ScottGibb** [embassy-rs/trouble#154]
Hi All,

Similar to bt-hci https://github.com/embassy-rs/bt-hci/issues/20, would there be any value in adding a CI stage to publish to crates.io.

I notice at the moment Trouble has got a placeholder on crates.io. Adding this CI Stage could be very useful for when this project increments in the future.

**Comment by lulf** [comment]
Agreed, it would be nice to have this.

**Comment by ScottGibb** [comment]
I think we can close this now @lulf  :)
