### ISSUE TITLE
Naming is trouble-some?

### ISSUE THREAD

**Issue by lure23** [embassy-rs/trouble#189]
I'm a newcomer to TrouBLE.

I don't oppose the name itself, but it causes consistent trouble *pun* in googling for solutions. Search engines cannot distinguish between "trouble" in BLE in general, and things concerning this particular library.

Also, I just realized that the essence of TrouBLE is being a host-side library (of HCI). This could be - if naming is ever reconsidered - somehow be included in the name itself. HBLE

**Comment by lulf** [comment]
Well, trouble-host is the host side, to leave the option available to write a trouble-controller or similar for anyone interested.

I understand this is a problem for googling, but I _really_ like the name `trouble` 😆

**Comment by wuwbobo2021** [comment]
Could you please explain about the reason why you really like the `trouble` naming in the `README.md` introduction? Realistic troubles are sometimes horrible or terrible, and I believe that no one wants to introduce real trouble into their projects if they want to do well. If I dare to guess it boldly based on my shallow understandings, did you mean the issues about BLE stack are troublesome by nature? Or, does it mean “one might not assume his work to be stable without experiencing troubles", just like the joke "one can't say trust without Rust"?

Anyway, it is interesting if I can see the qualified `trouble` being advertised in the future. However, I am almost sure that some people (who have had personal troubles in their lives and will never think about trouble as a friend anymore) will dislike this naming.

**Comment by lulf** [comment]
Yes, I do find that it's a fun pun on BLE being somewhat troublesome to deal with at times. If you do not like the name, and that is blocking you from using it, that is on you. This is open source, so you are of course free to fork and rename if you wish.
