### ISSUE TITLE
Example for esp32

### ISSUE THREAD

**Issue by lulf** [embassy-rs/trouble#32]

**Comment by artisdom** [comment]
Interested to get this running on esp32, not sure where to start. :)

**Comment by lulf** [comment]
I suggest to look at the [bleps example](https://github.com/bjoernQ/bleps/tree/main/esp32s3-serial-hci) as the starting point. You basically you need to provide Trouble with an implementation of a SerialTransport as done [here](https://github.com/embassy-rs/trouble/blob/main/examples/serial-hci/src/main.rs#L52-L55).

The ESP32 HAL already implements the Read and Write traits required I think, but it needs to be able to 'split' them to use with SerialTransport.

**Comment by Sycrosity** [comment]
@artisdom did you have any success with this?

**Comment by artisdom** [comment]
@Sycrosity have been distracted by other things from this, but would be keen to try it out if anyone got it working. :)

**Comment by lulf** [comment]
I've added an implementation of bt-hci traits to esp-hal https://github.com/esp-rs/esp-hal/pull/1971 , and a PR with trouble example in #81.

**Comment by Sycrosity** [comment]
@lulf amazing! I was attempting to work on this myself hack-ily but this is a much better result - thanks for the work!
