### ISSUE TITLE
`Advertiser::drop` always assumes extended advertising

### ISSUE THREAD

**Issue by Univa** [embassy-rs/trouble#66]
The `Drop` implementation for `Advertiser` calls `self.advertise_command_state.cancel(true)`. The `true` boolean value corresponds to extended advertising, based on the [`run_with_handler` implementation](https://github.com/embassy-rs/trouble/blob/cee020a40174976e30402dd85584a70040a81058/host/src/host.rs#L982).

In scenarios where you are not using extended advertising, the host could send an `LeSetExtAdvEnable` (with a `false` value) command, if the `Advertiser` struct gets dropped.

For example, this can cause issues with the `apache-nimble` controller:

```rust
let conn = adapter
    .advertise(
        &Default::default(),
        Advertisement::ConnectableScannableUndirected {
            adv_data: &adv_data,
            scan_data: &[],
        },
    )
    .await
    .unwrap()
    .accept()
    .await
    .unwrap();
```

Since the code above will call `Advertiser::drop`, the host will send the `LeSetExtAdvEnable` command, then the `apache-nimble` controller would return a "Command Disallowed" error.

**Comment by lulf** [comment]
Thanks for the report. This is a regression after I introduced the advertiser. It should be changed to know which kind of advertiser it is and pass that on when signalling the cancel. Either a bool param, or a generic param on the Advertiser, I think I prefer the bool param.
